### ISSUE TITLE
Druid gets stuck and does nothing when facing to a wall and summoning ravens

### ISSUE THREAD

**Issue by franva** [blizzhackers/kolbot#144] opened 2020-07-25 08:45 UTC
![image](https://user-images.githubusercontent.com/5151146/88453003-b41e5080-cea6-11ea-84dc-b915a164948e.png)

I have observed 3 times, my druid stands still and faces a wall, does nothing.

If I move it away from the wall, and manually summon another raven, then the bot was back to normal.

I suspend it has something with the code when summoning ravens.

**Comment by ryancrunchi** [comment] 2020-07-25 17:04
Hello,
I have faced this issue few months ago (years ?).
The problem is that bot tries to left click on a coordinate that is not clickable (or walkable) and the game ignores it. You can try to manually summon outside a room it will do nothing.
I fixed on my local branch by adding different coordinates to click if precast fail (if summoned units count does not increase).
The same may happen with amazon trying to summon Valkyrie.

**Comment by franva** [comment] 2020-07-26 00:31
beautiful~!  could you please pass the code? or opening a Pull Request(PR) for that?

For a bug like this, it is definitely worth of a PR.

Cheers~!

**Comment by DarkHorseDre** [comment] 2020-11-17 15:31
@ryancrunchi I've not looked at the code but know some casts are random locations - would changing raven cast to `me.x` and `me.y` fix this? (as those locations always exist and dont conflict)

**Comment by mf022** [comment] 2021-06-09 09:33
unfortunately, the druid's raven skill doesn't help too much. Most of the time it could be avoided, because of useless time consuming.
```
Config.SummonRaven = false;
```

**Closed by mf022** 2021-06-09 09:33 UTC
